[package]
name = "rsfgseapy"
version = "0.4.0"
edition = "2024"
rust-version = "1.97.1"
authors = ["Denis Demin"]
description = "Python bindings for rsfgsea"
license = "MIT"
documentation = "https://github.com/deminden/rsfgsea/tree/main/docs"
homepage = "https://github.com/deminden/rsfgsea"
repository = "https://github.com/deminden/rsfgsea"

[lib]
name = "rsfgseapy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.0", features = ["extension-module"] }
rsfgsea = { path = "../rsfgsea" }
rayon = "1.12.0"

[features]
gpu = ["rsfgsea/gpu"]
