# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rsfgseaR_wrappers", use_symbols = TRUE, package_name = "rsfgseaR")

#' @usage NULL
#' @useDynLib rsfgseaR, .registration = TRUE
NULL

#' Return the backend crate version.
#' @export
rsfgsea_version <- function() .Call(wrap__rsfgsea_version)

#' Return the supported execution modes.
#' @export
supported_modes <- function() .Call(wrap__supported_modes)

#' Run fgsea-compatible enrichment using a named stats vector and a GMT file.
#' @noRd
fgsea_rust <- function(stats, genes, gmt_path, n_perm_simple, seed, nproc, min_size, max_size, eps, score_type, gsea_param, mode, nperm, sample_size, sample_kind, gpu, method, decor_cache, decor_expression, decor_alpha, decor_cache_mode, decor_correlation, decor_redundancy) .Call(wrap__fgsea_rust, stats, genes, gmt_path, n_perm_simple, seed, nproc, min_size, max_size, eps, score_type, gsea_param, mode, nperm, sample_size, sample_kind, gpu, method, decor_cache, decor_expression, decor_alpha, decor_cache_mode, decor_correlation, decor_redundancy)

#' Write a single-pathway enrichment plot as PNG.
#' @noRd
write_enrichment_plot <- function(stats, genes, pathway_genes, output_path, pathway_name, score_type, gsea_param, width_inches, height_inches, dpi, transparent_background, title) .Call(wrap__write_enrichment_plot, stats, genes, pathway_genes, output_path, pathway_name, score_type, gsea_param, width_inches, height_inches, dpi, transparent_background, title)

#' Write a multi-pathway GSEA table plot as PNG.
#' @noRd
write_gsea_table_plot <- function(stats, genes, pathway_names, pathway_gene_lists, result_pathways, result_nes, result_pval, result_padj, output_path, gsea_param, width_inches, height_inches, dpi, transparent_background) .Call(wrap__write_gsea_table_plot, stats, genes, pathway_names, pathway_gene_lists, result_pathways, result_nes, result_pval, result_padj, output_path, gsea_param, width_inches, height_inches, dpi, transparent_background)


# nolint end
