# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rsfgseaR_wrappers", use_symbols = TRUE, package_name = "rsfgseaR")

#' @usage NULL
#' @useDynLib rsfgseaR, .registration = TRUE
NULL

#' Return the backend crate version.
#' @export
rsfgsea_version <- function() .Call(wrap__rsfgsea_version)

#' Return the supported execution modes.
#' @export
supported_modes <- function() .Call(wrap__supported_modes)

#' Run fgsea-compatible enrichment using a named stats vector and a GMT file.
#' @noRd
fgsea_rust <- function(stats, genes, gmt_path, n_perm_simple, seed, nproc, min_size, max_size, eps, score_type, gsea_param, mode, nperm, sample_size, gpu) .Call(wrap__fgsea_rust, stats, genes, gmt_path, n_perm_simple, seed, nproc, min_size, max_size, eps, score_type, gsea_param, mode, nperm, sample_size, gpu)


# nolint end
